import pytest
from filters import rus_language


@pytest.mark.parametrize(
    "text, expected",
    [
        ("То були мы разом", True),
        ("этот или тот", True),
        ("ъ", True),
        ("ё", True),
        ("э", True),
        ("ы", True),
        ("моё или твоє", True),
        ("потому что", True),
        ("как то так", True),
        ("да или нет", True),
        ("почему", True),
        ("вот как то так", True),
        ("только сегодня", True),
        ("только здесь", True),
        ("только сейчас", True),
        ("я теперь счастлив", True),
        ("ти никогда не пил кофе", True),
        ("Я очень люблю кофе", True),
        ("когда я пью кофе", True),
        ("мі там где хорошо", True),
        ("да нет", True),
        ("я конечно тут", True),
        ("наверное", True),
        ("дайте пожалуйста", True),
        ("скажу вам спасибо", True),
        ("я человек", True),
        ("жизнь", True),
        ("такой", True),
        ("могу", True),
        ("понимаю", True),
        ("должен", True),
        ("нужен", True),
        ("говоря", True),
        ("личку", True),
        ("работа", True),
        ("каждую", True),
        ("Паляниця", False),
        ("Укрзалізниця", False),
        ("привіт", False),
        (
            "Привіт усім! Підкажіть, будь ласка, як краще налаштувати aiogram для роботи з базою даних? Буду вдячний за допомогу.",
            False,
        ),
        ("🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥", False),
    ],
)
def test_rus_language(text, expected):
    assert rus_language(text) == expected
